export const HEALTH_INDICATORS = Symbol('HEALTH_INDICATORS');
export const HEALTH_MONITOR_CONFIG = Symbol('HEALTH_MONITOR_CONFIG');
export const HEALTH_SNAPSHOT_REPOSITORY = Symbol('HEALTH_SNAPSHOT_REPOSITORY');
export const RECOVERY_HISTORY_REPOSITORY = Symbol(
  'RECOVERY_HISTORY_REPOSITORY',
);
export const INTERNET_CHECK_URL = Symbol('INTERNET_CHECK_URL');

export const DEFAULT_INTERNET_CHECK_URL = 'https://www.google.com';
