export const SCHEDULED_JOBS = Symbol('SCHEDULED_JOBS');
export const SCHEDULER_CONFIG = Symbol('SCHEDULER_CONFIG');
export const SCHEDULER_HISTORY_REPOSITORY = Symbol(
  'SCHEDULER_HISTORY_REPOSITORY',
);

export const SCHEDULER_ENABLED_FLAG = 'SCHEDULER_ENABLED';
export const MORNING_STARTUP_ENABLED_FLAG = 'MORNING_STARTUP_ENABLED';
export const MARKET_CLOSE_ENABLED_FLAG = 'MARKET_CLOSE_ENABLED';
export const HEALTH_MONITOR_ENABLED_FLAG = 'HEALTH_MONITOR_ENABLED';
export const AUTOMATIC_RECOVERY_ENABLED_FLAG = 'AUTOMATIC_RECOVERY';
export const AUTOMATIC_RECONNECT_ENABLED_FLAG = 'AUTOMATIC_RECONNECT';
export const INSTRUMENT_REFRESH_ENABLED_FLAG = 'INSTRUMENT_REFRESH_ENABLED';
