export enum ValidationFailureCode {
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  INSTRUMENT_NOT_FOUND = 'INSTRUMENT_NOT_FOUND',
  MARKET_CLOSED = 'MARKET_CLOSED',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  INVALID_ENTRY_PRICE = 'INVALID_ENTRY_PRICE',
  INVALID_STOP_LOSS = 'INVALID_STOP_LOSS',
  INVALID_TARGETS = 'INVALID_TARGETS',
  DUPLICATE_ACTIVE_TRADE = 'DUPLICATE_ACTIVE_TRADE',
  RISK_LIMIT_EXCEEDED = 'RISK_LIMIT_EXCEEDED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  /** Phase 11's Risk Management Engine rejected the trade — distinct from the legacy RISK_LIMIT_EXCEEDED (Phase 7's simpler, hardcoded-per-mode RiskRule) so a consumer can tell which gate actually rejected it. */
  RISK_MANAGEMENT_REJECTED = 'RISK_MANAGEMENT_REJECTED',
}
