export enum QueueItemState {
  QUEUED = 'QUEUED',
  LOCKED = 'LOCKED',
  PROCESSING = 'PROCESSING',
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  RETRYING = 'RETRYING',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
