import { inspect } from 'node:util';

/**
 * Wraps DhanHQ's credentials. DhanHQ auth is a static, externally-generated
 * access token (generated by the user in the Dhan web console, not via a
 * password+TOTP login flow) plus a client ID — there is no password/TOTP to
 * protect here, but the access token is still a secret, so the same
 * redaction discipline applies: it's a private field with an explicit
 * getter, and toJSON()/toString()/util.inspect are all overridden so an
 * accidental console.log(credentials) or JSON.stringify(credentials) cannot
 * leak it.
 */
export class BrokerCredentials {
  constructor(
    public readonly clientId: string,
    public readonly apiKey: string,
    private readonly accessToken: string,
  ) {}

  getAccessToken(): string {
    return this.accessToken;
  }

  toJSON(): Record<string, unknown> {
    return {
      clientId: this.clientId,
      apiKey: this.apiKey,
      accessToken: '[REDACTED]',
    };
  }

  toString(): string {
    return `BrokerCredentials(clientId=${this.clientId})`;
  }

  [inspect.custom](): string {
    return this.toString();
  }
}
